Rename the name and namespace for sqlite as per new convention introduced
astronomer/astro-sdk pull request #1306
Opened 2022-11-24 09:34 UTC by rajaths010494

Describe the bug
There have been new conventions introduced: [Naming.md#local-file-system](https://github.com/OpenLineage/OpenLineage/blob/main/spec/Naming.md#local-file-system)
I believe sqlite counts as local file, therefore you could adjust naming convention in astro as well.

A word of explanation: both IP and port are mandatory. It means that if port is unknown (e. g. if file exists in Airflow's local file system only) you should default to some value. In one of OL extractors it is defaulted to paramiko.config.SSH_PORT, in most cases it's equal to 22.

Reference: https://github.com/astronomer/astro-sdk/pull/1142#issuecomment-1321563229

closes #1281

2022-11-24 09:44 UTC, JDarDagran approved these changes
LGTM

2022-11-24 09:44 UTC, JDarDagran commented on python-sdk/src/astro/databases/sqlite.py
> +        port = conn.port if conn.port else 22
simpler is `conn.port or 22`

2022-11-24 10:04 UTC, rajaths010494 commented on python-sdk/src/astro/databases/sqlite.py
> +        port = conn.port if conn.port else 22
changed

2022-11-24 11:58 UTC, rajaths010494 commented
Attaching a screenshot of the URI for reference on Marquez UI.
<img width="2556" alt="image" src="https://user-images.githubusercontent.com/92459020/203778983-cba83705-fb24-4d6a-916a-d5666a924c11.png">

2022-11-25 09:36 UTC, sunank200 approved these changes
LGTM

2022-11-25 09:38 UTC, sunank200 commented
@rajaths010494 @JDarDagran is the `dataSource` `uri` in the correct format as aspected?

2022-11-25 10:05 UTC, JDarDagran commented
Actually why do you need this format:
```
f"{self.input_data.openlineage_dataset_namespace()}"
f"://{self.input_data.openlineage_dataset_name()}"
```
with two slashes before dataset name? The path should be absolute so I'd rather see URI as `file://172.26.0.2:22/tmp/sqlite.db.top_animation`.

2022-11-25 10:55 UTC, sunank200 requested changes
> Actually why do you need this format:
> 
> ```
> f"{self.input_data.openlineage_dataset_namespace()}"
> f"://{self.input_data.openlineage_dataset_name()}"
> ```
> 
> with two slashes before dataset name? The path should be absolute so I'd rather see URI as `file://172.26.0.2:22/tmp/sqlite.db.top_animation`.
> 
> [This](https://www.rfc-editor.org/rfc/rfc3986.txt) spec, 3.3. Path explains more.

@rajaths010494 we should do this change across.

2022-11-25 11:06 UTC, rajaths010494 commented
> > Actually why do you need this format:
> > ```
> > f"{self.input_data.openlineage_dataset_namespace()}"
> > f"://{self.input_data.openlineage_dataset_name()}"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with two slashes before dataset name? The path should be absolute so I'd rather see URI as `file://172.26.0.2:22/tmp/sqlite.db.top_animation`.
> > [This](https://www.rfc-editor.org/rfc/rfc3986.txt) spec, 3.3. Path explains more.
> 
> @rajaths010494 we should do this change across.

Yeah saw i will make the necessary changes

2022-11-25 11:13 UTC, rajaths010494 commented
> > > Actually why do you need this format:
> > > ```
> > > f"{self.input_data.openlineage_dataset_namespace()}"
> > > f"://{self.input_data.openlineage_dataset_name()}"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > with two slashes before dataset name? The path should be absolute so I'd rather see URI as `file://172.26.0.2:22/tmp/sqlite.db.top_animation`.
> > > [This](https://www.rfc-editor.org/rfc/rfc3986.txt) spec, 3.3. Path explains more.
> > 
> > 
> > @rajaths010494 we should do this change across.
> 
> Yeah saw i will make the necessary changes

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/92459020/203973671-290d682c-aa81-4d36-8fbc-492dd1af690d.png">
Does this look fine.  @JDarDagran @sunank200 . If yes i will make the necessary changes.

2022-11-25 11:16 UTC, JDarDagran commented
> > > > Actually why do you need this format:
> > > > ```
> > > > f"{self.input_data.openlineage_dataset_namespace()}"
> > > > f"://{self.input_data.openlineage_dataset_name()}"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > with two slashes before dataset name? The path should be absolute so I'd rather see URI as `file://172.26.0.2:22/tmp/sqlite.db.top_animation`.
> > > > [This](https://www.rfc-editor.org/rfc/rfc3986.txt) spec, 3.3. Path explains more.
> > > 
> > > 
> > > @rajaths010494 we should do this change across.
> > 
> > 
> > Yeah saw i will make the necessary changes
> 
> <img alt="image" width="1671" src="https://user-images.githubusercontent.com/92459020/203973671-290d682c-aa81-4d36-8fbc-492dd1af690d.png">
> 
> Does this look fine. @JDarDagran @sunank200 . If yes i will make the necessary changes.

👍

2022-11-28 11:28 UTC, sunank200 requested changes
@rajaths010494 Change looks good to me.But lets add the test for this change.

2022-11-29 10:33 UTC, sunank200 commented
We should create a method for URI for each database and use that. I will do that change and push it

2022-11-29 11:42 UTC, sunank200 commented
Ran and tested the example DAGs for operators on Marquez.
<img width="2549" alt="image" src="https://user-images.githubusercontent.com/8670962/204518214-f2545d6e-e108-48dd-b376-16ea11a521fb.png">
<img width="2551" alt="image (1)" src="https://user-images.githubusercontent.com/8670962/204518299-a89b123f-c666-4df5-9c24-7ed7b3d9755f.png">

2022-11-29 11:48 UTC, rajaths010494 commented
LGTM

2022-11-29 11:48 UTC, sunank200 approved these changes

2022-11-29 11:55 UTC, phanikumv approved these changes

2022-11-29 21:50 UTC, merged