Fix snowflake stage not being deleted on error in load_file
astronomer/astro-sdk pull request #1321
Opened 2022-11-29 09:57 UTC by feluelle

# Description

## What is the current behavior?

Currently the snowflake stage is not being dropped incase of an exception when calling `load_file`.

closes: #1262

## What is the new behavior?

Drop snowflake stage also when file load failed.

## Does this introduce a breaking change?

No.

### Checklist
- [x] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2022-11-29 10:21 UTC, sunank200 approved these changes
LGTM

2022-11-29 11:52 UTC, tatiana approved these changes

2022-11-29 13:24 UTC, kaxil reviewed
One of the test is failing - https://github.com/astronomer/astro-sdk/actions/runs/3572950837/jobs/6007534322

2022-11-29 14:16 UTC, feluelle commented on python-sdk/src/astro/databases/snowflake.py
> -            except (AttributeError, ValueError) as exe:
@kaxil @utkarsharma2 @sunank200 maybe?

2022-11-29 19:52 UTC, sunank200 requested changes
`AttributeError` would be required as this is raised by snowflake for which we should fallback if enabled by the user. Related to #1324

2022-11-29 19:52 UTC, sunank200 commented on python-sdk/src/astro/databases/snowflake.py
> -            except (AttributeError, ValueError) as exe:
It's required as this is raised by snowflake for which we should fallback if enabled by the user. Related to https://github.com/astronomer/astro-sdk/pull/1324

2022-11-30 10:51 UTC, sunank200 commented on python-sdk/src/astro/databases/snowflake.py
> -            except (AttributeError, ValueError) as exe:
Tested it now its working without `AttributeError`

2022-11-30 10:52 UTC, sunank200 approved these changes

2022-11-30 10:52 UTC, sunank200 commented
> `AttributeError` would be required as this is raised by snowflake for which we should fallback if enabled by the user. Related to #1324

Tested it without `AttributeError` and it works so the change is fine

2022-11-30 10:52 UTC, merged