Add test case to verify the serialization working correctly
astronomer/astro-sdk pull request #1441
Opened 2022-12-16 12:59 UTC by utkarsharma2

# Description
## What is the current behavior?
RN, we don't have a test case to verify the serialization and deserialization are working correctly.

## What is the new behavior?
Added a test case to verify the serialization and deserialization

## Does this introduce a breaking change?
Nope

2022-12-16 13:51 UTC, kaxil commented on python-sdk/tests_integration/sql/operators/test_load_file.py
> +    test_utils.run_dag(sample_dag)
Does not have to been an integration test for sure!

2022-12-16 13:51 UTC, kaxil commented on python-sdk/tests_integration/sql/operators/test_load_file.py
> +    """
Doesn't add any value, says the same thing as the test name

2022-12-22 18:59 UTC, dimberman requested changes

2022-12-22 18:59 UTC, dimberman commented on python-sdk/tests_integration/sql/operators/test_load_file.py
> +    test_utils.run_dag(sample_dag)
@utkarsharma2 aas Kaxil mentioned. Ultimately we are just serializing data into json and then deserializing it from json. There is no need to create a DAG run and if anything that adds unnecessary overhead. Why not just serialize it into a json variable and ensure that the resulting json looks correct/can deserialize back to the same object?

2023-01-17 12:39 UTC, utkarsharma2 commented
No longer needed. Closing the PR.

2023-01-17 12:39 UTC, closed without merging