Add makefile
astronomer/astro-sdk pull request #220
Opened 2022-03-17 03:39 UTC by bhavaniravi

Fixes #213 
Adds Makefile to ease project setup

**To-Do**
1. Differentiate integration and unit-test
2. Better documentation of commands
3. Extensive Testing

2022-03-18 17:24 UTC, dimberman requested changes

2022-03-18 17:24 UTC, dimberman commented on Makefile
> +	. $(VENV)/bin/activate
Should venv be an env variable? Can we make it an argument?

e.g. `make activate --venv dev`

2022-03-23 09:32 UTC, tatiana commented on Makefile
> +	pytest -s --cov-report term --cov-branch -m "not integration"
What do you think about using  `--cov-report term-missing` so we can see any implicit code branches that the tests might not be covering?

2022-03-25 14:10 UTC, tatiana approved these changes
It's a great beginning, @bhavaniravi , thank you very much!
Do you have any ideas about how we can improve it in the future, to handle the `.env` and `test-connections.yaml` files?

2022-07-29 15:10 UTC, pankajastro commented
LGTM

2022-07-29 15:10 UTC, pankajastro approved these changes

2022-07-29 19:59 UTC, dimberman approved these changes

2022-08-01 10:09 UTC, merged